#!/bin/bash

# A launcher for the phoebus container that allows X11 forwarding

thisdir=$(realpath $(dirname ${0}))

# assume podman for now - change this to docker if needed
docker=podman
args="--security-opt=label=type:container_runtime_t"

XSOCK=/tmp/.X11-unix # X11 socket (but we mount the whole of tmp)
XAUTH=/tmp/.container.xauth.$USER
touch $XAUTH
xauth nlist $DISPLAY | sed -e 's/^..../ffff/' | xauth -f $XAUTH nmerge -
chmod 777 $XAUTH

x11="
-e DISPLAY
-v $XAUTH:$XAUTH
-e XAUTHORITY=$XAUTH
-v /run/dbus/system_bus_socket:/run/dbus/system_bus_socket
--net host
"

args=${args}"
-it
--pull newer
"

export MYHOME=/home/${USER}
# mount in your own home dir in same folder for access to external files
# also mount in the podman socket as the default Docker socket
# for podman-outside-docker
mounts="
-v=/tmp:/tmp
-v=${MYHOME}/.ssh:/root/.ssh
-v=${MYHOME}/.config:/root/.config
-v=${MYHOME}/.cache:/root/.cache
-v=${MYHOME}:${MYHOME}
-v=/scratch:/scratch
-v=/dls_sw:/dls_sw
-v=${thisdir}:/workspace
-v=${XDG_RUNTIME_DIR}/podman/podman.sock:/var/run/docker.sock
"

xhost +SI:localuser:$(id -un)

set -x
$docker run ${mounts} ${args} ${x11} ${@} ghcr.io/epics-containers/zed:latest
